# DataFrames III: Data Extraction

In [ ]:
import pandas as pd

## This Module's Dataset
- This module's dataset is a collection of all James Bond movies.

## 이 모듈의 데이터셋
- 이 모듈의 데이터셋은 모든 제임스 본드 영화 모음입니다.

In [ ]:
bond = pd.read_csv("jamesbond.csv")
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

## Overwrite Value in a DataFrame
- Use the `iloc` or `loc` accessor on the **DataFrame** to target a value, then provide the equal sign and a new value.

## 데이터프레임의 값 덮어쓰기
- **DataFrame**에 대해 `iloc` 또는 `loc` 접근자를 사용하여 값을 지정한 후, 등호와 새 값을 제공합니다.

In [ ]:
bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

* "Diamonds Are Forever" 의 "Actor" 를 "Sir Sean Connery" 로 변경해보라.

In [ ]:
# 여기에

* 변경되었는지 확인해보자.

In [ ]:
# 여기에

##  Overwrite Multiple Values in a DataFrame
- The `replace` method replaces all occurrences of a **Series** value with another value (think of it like "Find and Replace").
- To overwrite multiple values in a **DataFrame**, remember to use an accessor on the **DataFrame** itself.
- Accessors like `loc` and `iloc` can accept Boolean Series. Use them to target the values to overwrite.

## 데이터프레임의 여러 값 덮어쓰기
- `replace` 메서드는 **Series**의 모든 값을 다른 값으로 바꿉니다 ("찾아 바꾸기"처럼 생각하세요).
- **DataFrame**의 여러 값을 바꾸려면 접근자를 사용해야 합니다.
- `loc` 및 `iloc` 같은 접근자는 불리언 Series를 받을 수 있어, 특정 값을 타겟팅할 수 있습니다.

In [ ]:
bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

* Sean Connery 를 Sir Sean Connery 로 변형하라 -> replace() 사용

In [ ]:
# 여기에

* 모든 Sean Connery 부분을 loc 을 사용하여, Sir Sean Connery 로 변형하라.

In [ ]:
# 여기에

* 다시 index 를 Film 으로 설정해서 파일을 다시 불러온 후, Actor 가 Sean Connery 인 부분을 모두 필터로 설정하여, 해당 부분의 Actor 부분을 Sir Sean Connery 로 변경하라.

In [ ]:
# 여기에

* 변경이 되었는지 확인해보자.

In [ ]:
# 여기에

## Rename Index Labels or Columns in a DataFrame
- The `rename` method accepts a dictionary for either its `columns` or `index` parameters.
- The dictionary keys represent the existing names and the values represent the new names.
- We can replace all columns by overwriting the **DataFrame's** `columns` attribute.

## 데이터프레임의 인덱스 라벨이나 열 이름 바꾸기
- `rename` 메서드는 `columns` 또는 `index` 파라미터에 딕셔너리를 전달받습니다.
- 딕셔너리의 키는 기존 이름이고 값은 새로운 이름입니다.
- **DataFrame**의 `columns` 속성을 덮어써 모든 열을 한꺼번에 바꿀 수 있습니다.

In [ ]:
# 일단 깨끗한 데이터 다시 불러오기
bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

* 여기서 rename() 을 사용하여 column 의 Year -> Year of Releaase, Box Office -> Revenue 로 바꿔보자.

In [ ]:
# 여기에

* index 의 Dr. No -> Dr No, GoldenEye -> Golden Eye, The World Is Not Enough -> Best Bond Movie Ever 로 replace 를 적용하여 수정해보자.

In [ ]:
# 여기에

* 컬럼의 이름을 "Year", "Bond Guy", "Camera Dude", "Revenues", "Cost", "Salary" 로 한번에 수정해보자.

In [ ]:
# 여기에

In [ ]:
bond.head()

,Year,Bond Guy,Camera Dude,Revenues,Cost,Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

## Create Random Sample with the sample Method
- The `sample` method returns a specified one or more random rows from the **DataFrame**.
- Customize the `axis` parameter to extract random columns.

## sample 메서드를 사용한 무작위 샘플 생성
- `sample` 메서드는 **DataFrame**에서 하나 이상의 무작위 행을 반환합니다.
- `axis` 파라미터를 지정하면 무작위 열을 추출할 수 있습니다.

In [ ]:
bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

* 다음 sample() 의 예제를 사용하여 각각 어떤 샘플링이 되는지 확인해보자.

In [ ]:
# 설명
bond.sample()

In [ ]:
# 설명
bond.sample(n=5)

In [ ]:
# 설명
bond.sample(n=3, axis="rows")

In [ ]:
# 설명

bond.sample(n=2, axis="columns")

## The nsmallest and nlargest Methods
- The `nlargest` method returns a specified number of rows with the largest values from a given column.
- The `nsmallest` method returns rows with the smallest values from a given column.
- The `nlargest` and `nsmallest` methods are more efficient than sorting the entire **DataFrame**.

## nsmallest 및 nlargest 메서드
- `nlargest` 메서드는 주어진 열에서 가장 큰 값을 가진 행들을 반환합니다.
- `nsmallest` 메서드는 가장 작은 값을 가진 행들을 반환합니다.
- 이 메서드들은 전체 **DataFrame**을 정렬하는 것보다 더 효율적입니다.

In [ ]:
bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

* Box Office 수익이 가장 큰 네개를 sort_values() 를 써서 추출해보자.

In [ ]:
# 여기에

* 동일한 형태를 nlargest() 를 통해 Box Office 에서 가장 큰 4개 값을 뽑아보자.

In [ ]:
# 여기에

* 반대로 nsmallest 를 사용하여 Bond Actor Salary 의 가장 작은 값 세개를 추출하라.

In [ ]:
# 여기에

## Filtering with the where Method
- Similar to square brackets or `loc`, the `where` method filters the original `DataFrame` with a Boolean Series.
- Pandas will populate rows that do **not** match the criteria with `NaN` values.
- Leaving in the `NaN` values can be advantageous for certain merge and visualization operations.

## where 메서드를 사용한 필터링
- 대괄호나 `loc`와 유사하게 `where` 메서드는 Boolean Series를 사용해 원본 `DataFrame`을 필터링합니다.
- 조건에 맞지 않는 행은 `NaN`으로 채워집니다.
- `NaN` 값을 남겨두는 것은 병합이나 시각화에서 유용할 수 있습니다.

In [ ]:
bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

* Actor 가 Sean Connery 인 필터를 만든 후, where 에 해당 필터를 적용하여 이에 해당하는 부분만 추출해보라.

In [ ]:
#  여기에

* 동일 기능을 loc 으로 적용해보라.

In [ ]:
# 여기에

## The apply Method with DataFrames
- The `apply` method invokes a function on every column or every row in the **DataFrame**.
- Pass the uninvoked function as the first argument to the `apply` method.
- Pass the `axis` parameter an argument of `"columns"` to invoke the function on every row.
- Pandas will pass in the row's values as a **Series** object. We can use accessors like `loc` and `iloc` to extract the column's values for that row.

## 데이터프레임에서 apply 메서드 사용
- `apply` 메서드는 **DataFrame**의 각 열이나 행에 함수를 적용합니다.
- 호출하지 않은 함수 객체를 첫 번째 인자로 전달합니다.
- `axis="columns"`를 설정하면 각 행에 대해 함수를 적용합니다.
- Pandas는 행의 값을 **Series** 객체로 전달하며, `loc`와 `iloc` 같은 접근자로 해당 값을 추출할 수 있습니다.

In [ ]:
bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

* Actor 열에 len 함수를 한번에 적용하기 위해 apply 를 적용해보자.

In [ ]:
# 여기에

In [ ]:
bond.head(1)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1

* 간단한 함수를 만들어서, 각 행을 평가하도록 apply 를 적용해보자.

In [ ]:
# MOVIE RANKING SYSTEM
#
# CONDITION      -> DESIGNATION
# 80s movie      -> "Great 80's flick"
# Pierce Brosnan -> "The best Bond ever"
# Budget > 100   -> "Expensive movie, fun"
# Others         -> "No comment"

def rank_movie(row):
    year = row.loc["Year"]
    actor = row.loc["Actor"]
    budget = row.loc["Budget"]

    if year >= 1980 and year < 1990:
        return "Great 80's flick!"

    if actor == "Pierce Brosnan":
        return "The best Bond ever!"

    if budget > 100:
        return "Expensive movie, fun"

    return "No comment"

In [ ]:
# 여기에